// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxmlvusividgvxvzgqht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bWx2dXNpdmlkZ3Z4dnpncWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NjYxNjksImV4cCI6MjA1NTM0MjE2OX0.pQhRxce3znyMgeQ8JUYaQCPkOocc_gqrmf91fiH6EI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);