
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqwitgafexdvnmbnbpie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxd2l0Z2FmZXhkdm5tYm5icGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTE5NDksImV4cCI6MjA2NTY2Nzk0OX0.tIwM97KsRkwkn-PjmITN4GZ3NPPyS2xIklLtJciGZm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
