// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obeyfmmweyhebspeafnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZXlmbW13ZXloZWJzcGVhZm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Nzk5NDAsImV4cCI6MjA2NTE1NTk0MH0.eODisV-nJdoEswwDGuLozQnBSLJfKl4yybHKtm-pa68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);